chave_api = "15c6017e98f71b19d6b7f16932ff4aaa"
token = ""

# Opções para o tipo de identificação
OPTIONS_IDENTIFICACAO = ["Selecione uma opção", "CPF", "ID FUNCIONAL"]

OPTIONS_CONVENIO = [
    "Selecione um Convênio",
    "12 BPM - RAS",
    "25 BPM - RAS",
    "MUNICÍPIO DE ARARUAMA",
    "MUNICÍPIO DE IGUABA GRANDE",
    "MUNICIPIO DE NITEROI",
    "PREFEITURA DE MARICÁ",
    "PREFEITURA DE SAQUAREMA",
]
""" OPTIONS_CONVENIO = [
    "Selecione um Convênio",
    "01 CIPM - RAS",
    "01 CPA - RAS",
    "01 DPJM - RAS",
    "01 UPP 16 BPM FAZENDINHA - RAS",
    "01 UPP 19 OPM BABILONIA RAS",
    "01 UPP 2 BPM SANTA MARTA - RAS",
    "01 UPP 22 BPM ADEUS BAIANA - RAS",
    "01 UPP 23 BPM VIDIGAL - RAS",
    "01 UPP 4 BPM TURANO - RAS",
    "01 UPP 5 BPM PROVIDÊNCIA - RAS",
    "01 UPP 6 BPM BOREL - RAS",
    "01 UPP DO 3 BPM SAO JOAO RAS",
    "02 BPM - RAS",
    "02 CIPM - RAS",
    "02 CPA - RAS",
    "02 DPJM - RAS",
    "02 UPP 16 BPM NOVA BRASILIA - RAS",
    "02 UPP 19 BPM PAVAO PAVAOZINHO CANTAGALO - RAS",
    "02 UPP 22 BPM MANGUINHOS - RAS",
    "02 UPP 23 BPM ROCINHA - RAS",
    "02 UPP 3 BPM JACAREZINHO - RAS",
    "02 UPP 6 BPM FORMIGA  RAS",
    "03 BPM - RAS",
    "03 CPA - RAS",
    "03 DPJM - RAS",
    "03 UPP 16 BPM ALEMAO - RAS",
    "03 UPP 19 BPM TABAJARAS - RAS",
    "03 UPP 22 BPM ARARA MANDELA - RAS",
    "03 UPP 3 BPM LINS- RAS",
    "03 UPP 4 BPM MANGUEIRA - RAS",
    "03 UPP 5 BPM PRAZERES ESCONDIDINHO - RAS",
    "03 UPP 6 BPM ANDARAI - RAS",
    "04 BPM - RAS",
    "04 CPA - RAS",
    "04 DPJM - RAS",
    "04 UPP 16 BPM FE E SERENO - RAS",
    "04 UPP 6 BPM SALGUEIRO - RAS",
    "05 BPM - RAS",
    "05 CPA - RAS",
    "05 DPJM - RAS",
    "05 UPP 16 BPM CHATUBA RAS",
    "05 UPP 4 BPM BARREIRA DO VASCO TUITI - RAS",
    "05 UPP 6 BPM MACACOS - RAS",
    "06 BPM - RAS",
    "06 CPA - RAS",
    "06 DPJM - RAS",
    "06 UPP 16 BPM PARQUE PROLETARIO - RAS",
    "07 BPM - RAS",
    "07 CPA - RAS",
    "07 UPP DO 16 BPM VILA CRUZEIRO RAS",
    "08 BPM - RAS",
    "09 BPM - RAS",
    "10 BPM - RAS",
    "11 BPM - RAS",
    "12 BPM - RAS",
    "14 BPM - RAS",
    "15 BPM - RAS",
    "16 BPM - RAS",
    "17 BPM - RAS",
    "18 BPM - RAS",
    "19 BPM - RAS",
    "20 BPM - RAS",
    "21 BPM - RAS",
    "22 BPM - RAS",
    "23 BPM - RAS",
    "24 BPM - RAS",
    "25 BPM - RAS",
    "26 BPM - RAS",
    "27 BPM - RAS",
    "28 BPM - RAS",
    "29 BPM - RAS",
    "30 BPM - RAS",
    "31 BPM - RAS",
    "32 BPM - RAS",
    "33 BPM - RAS",
    "34 BPM - RAS",
    "35 BPM - RAS",
    "36 BPM - RAS",
    "37 BPM - RAS",
    "38 BPM - RAS",
    "39 BPM - RAS",
    "40 BPM - RAS",
    "41 BPM - RAS",
    "7 DPJM - RAS",
    "8 DPJM",
    "AJUDÂNCIA GERAL - RAS",
    "APM - RAS",
    "BAC - RAS",
    "BEPE",
    "BOPE - RAS",
    "BPCHQ - RAS",
    "BPRV - RAS",
    "BPTUR - RAS",
    "BPVE - RAS",
    "CAES",
    "CCOMSOC - RAS",
    "CCPMERJ - MUSEU",
    "CCR VIA LAGOS",
    "CEADPM - RAS",
    "CEASA",
    "CECOPOM - RAS",
    "EDAE",
    "CEFD - RAS",
    "CETIC",
    "CFAP - RAS",
    "CFAP/CCPP",
    "CFRPM - RAS",
    "CGPM - RAS",
    "CIEAT - RAS",
    "CIESPP",
    "CIPM-MUS - RAS",
    "COE - RAS",
    "CONCESSIONÁRIA AEROPORTO RIO DE JANEIRO S.A",
    "CPAM - RAS",
    "CPE - RAS",
    "CPMERJ  CAMPO GRANDE",
    "CPMERJ DUQUE DE CAXIAS",
    "CPMERJ NITERÓI",
    "CPP - RAS",
    "CPROEIS",
    "CPTRANS",
    "DABST - RAS",
    "DAS RAS",
    "DCMUN",
    "DCP - RAS",
    "DEA - RAS",
    "DEFENSORIA PÚBLICA DO ESTADO DO RIO DE JANEIRO",
    "DF - RAS",
    "DGAF - RAS",
    "DGAL",
    "DGEI - RAS",
    "DGO - RAS",
    "DGP RAS",
    "DGS",
    "DIRETORIA DE LICITACOES E PROJETOS",
    "DIRETORIA DE TRANSPORTES",
    "DMP - RAS",
    "DMSA",
    "DOR - RAS",
    "DPA RAS",
    "DPAT - RAS",
    "DPPMERJ - RAS",
    "DRSP - RAS",
    "DVP",
    "EMG - RAS",
    "ESPM - RAS",
    "FAZ. MARAMBAIA - RAS",
    "GAM - RAS",
    "GCG - RAS",
    "GESAR - RAS",
    "GPFER",
    "HCPM - RAS",
    "HPM / NIT - RAS",
    "LEI SECA",
    "LIGHT",
    "LINHA AMARELA S/A",
    "METRÔRIO",
    ">MUNICÍPIO DE ARARUAMA",
    "MUNICIPIO DE ARRAIAL DO CABO",
    "MUNICÍPIO DE DUQUE DE CAXIAS",
    "MUNICÍPIO DE IGUABA GRANDE",
    "MUNICÍPIO DE MIGUEL PEREIRA",
    "MUNICIPIO DE NITEROI",
    "MUNICIPIO DE PARACAMBI",
    "MUNICÍPIO DE PAULO DE FRONTIN",
    "MUNICÍPIO DE SÃO JOÃO DA BARRA",
    "MUNICÍPIO DE TANGUÁ",
    "OCPM - RAS",
    "PPM / CASCADURA - RAS",
    "PPM / OLARIA - RAS",
    "PPM / SJM - RAS",
    "PPM/CAMPOS - RAS",
    "PREFEITURA ANGRA DOS REIS",
    "PREFEITURA DA CIDADE DO RIO DE JANEIRO II",
    "PREFEITURA DE BUZIOS",
    "PREFEITURA DE CABO FRIO",
    "REFEITURA DE CASIMIRO DE ABREU",
    "PREFEITURA DE CORDEIRO",
    "PREFEITURA DE ITAGUAÍ",
    "PREFEITURA DE MARICÁ",
    "PREFEITURA DE MESQUITA",
    "PREFEITURA DE NOVA IGUAÇÚ",
    "PREFEITURA DE PARATY",
    "PREFEITURA DE QUEIMADOS",
    "PREFEITURA DE QUISSAMÃ",
    "PREFEITURA DE RIO BONITO",
    "PREFEITURA DE RIO DAS OSTRAS",
    "PREFEITURA DE SAQUAREMA",
    "RECOM",
    "RPMONT - RAS",
    "SÃO JOÃO DE MERITI",
    "SEGURANÇA PRESENTE",
    "SETUR",
    "SSCC - RAS",
    "SSI - RAS",
    "SUPERVIA",
    "UNIVERSIDADE DO ESTADO DO NORTE FLUMINENSE",
    "UPPMERJ - RAS",
    "VIA RIO",
]
 """
OPTIONS_VAGASXCONVENIO = {
    "25 BPM - RAS": [
        "Selecione uma vaga",
        "CABO FRIO. POLICIAMENTO PREVENTIVO SOBRE MANCHA CRIMINAL",
        "SAQUAREMA. POLICIAMENTO PREVENTIVO SOBRE MANCHA CRIMINAL",
        "A. BUZIOS. POLICIAMENTO PREVENTIVO SOBRE MANCHA CRIMINAL",
        "ARRAIAL DO CABO. PATRULHAMENTO",
        "CNH A OBRIGATÓRIO POLICIAMENTO MANCHA CRIMINAL CABO FRIO MOTOS",
        "ARARUAMA.  POLICIAMENTO PREVENTIVO SOBRE MANCHA CRIMINAL",
        "QUADRICICLO BUZIOS",
        "UNAMAR. POLICIAMENTO PREVENTIVO MANCHA CRIMINAL",
        "QUADRICICLO SAQUAREMA",
        "CNH A OBRIGATÓRIO POLICIAMENTO MANCHA CRIMINAL BUZIOS",
        "CNH A OBRIGATÓRIO POLICIAMENTO MANCHA CRIMINAL SAQUAREMA",
        "IGUABA GRANDE. PATRULHAMENTO",
    ],
    "PREFEITURA DE MARICÁ": [
        "Selecione uma vaga",
        "CERCO INTELIGENTE",
        "MÓDULO CALABOCA",
        "MÓDULO DE SEGURANÇA UBATIBA",
        "MÓDULO DO CAJU",
        "MÓDULO DE SEGURANÇA CAJUEIRO",
        "MÓDULO DE SEGURANÇA SÃO JOSÉ",
        "PATRULHAMENTO MARICA",
        "PB ACESSO AO MCMV INOÃ",
        "SETOR CENTRO",
        "SETOR ITAIPUAÇU",
        "SETOR PONTA NEGRA",
        "SETOR SÃO JOSÉ DO IMBASSAÍ",
        "SETOR INOÃ",
        "SETOR UBATIBA",
        "SETOR BAMBUÍ",
        "SETOR ITAIPUAÇU ITAOCAIA",
    ],
    "MUNICIPIO DE NITEROI": [
        "Selecione uma vaga",
        "APOIO A INTERVENCAO URBANISTICA DA PRE. DE NITEROI",
        "NITEROI MAIS SEGURA",
        "BARCAS SA  E TERMINAL",
    ],
    "IMPRENSA OFICIAL RJ": ["Selecione uma vaga", "IMPRENSA OFICIAL SEDE"],
    "MUNICÍPIO DE ARARUAMA": [
        "Selecione uma vaga",
        "PATRULHAMENTO ARARUAMA MAIS SEGURA",
    ],
    "MUNICÍPIO DE IGUABA GRANDE": [
        "Selecione uma vaga",
        "PATRULHAMENTO  DIA E NOITE",
    ],
    "PREFEITURA DE SAQUAREMA": [
        "Selecione uma vaga",
        "MÓDULO JACAREPIÁ",
        "MÓDULO TREVO LATINO MELO",
        "VTR DE APOIO AO MODULO JACAREPIA",
        "SAQUAREMA MAIS SEGURA III",
        "MÓDULO TREVO VILATUR",
        "DEPÓSITO MAIS SEGURO",
    ],
}

OPTIONS_CPA = [
    "Selecione um Cpa",
    "12º BPM - 4º CPA",
    "25º BPM - 4º CPA",
]
""" OPTIONS_CPA = [
    "Selecione um Cpa",
    "10º BPM - 5º CPA",
    "11º BPM - 7º CPA",
    "12º BPM - 4º CPA",
    "14º BPM - 2º CPA",
    "15º BPM - 3º CPA",
    "16º BPM - 1º CPA",
    "17º BPM - 1º CPA",
    "18º BPM - 2º CPA",
    "19º BPM - 1º CPA",
    "2º BPM - 1º CPA",
    "20º BPM - 3º CPA",
    "21º BPM - 3º CPA",
    "22º BPM - 1º CPA",
    "23º BPM - 1º CPA",
    "24º BPM - 3º CPA",
    "25º BPM - 4º CPA",
    "26º BPM - 7º CPA",
    "27º BPM - 2º CPA",
    "28º BPM - 5º CPA",
    "29º BPM - 6º CPA",
    "3º BPM - 1º CPA",
    "30º BPM - 7º CPA",
    "31º BPM - 2º CPA",
    "32º BPM - 6º CPA",
    "33º BPM - 5º CPA",
    "34º BPM - 3º CPA",
    "35º BPM - 4º CPA",
    "36º BPM - 6º CPA",
    "37º BPM - 5º CPA",
    "38º BPM - 7º CPA",
    "39º BPM - 3º CPA",
    "4º BPM - 1º CPA",
    "40º BPM - 2º CPA",
    "41º BPM - 2º CPA",
    "5º BPM - 1º CPA",
    "6º BPM - 1º CPA",
    "7º BPM - 4º CPA",
    "8º BPM - 6º CPA",
    "9º BPM - 2º CPA",
]
 """

OPTIONS_LOCAISXCPA = {
    "12º BPM - 4º CPA": [
        "Selecione o local",
        "MUNICIPIO DE NITEROI",
        "IMPRENSA OFICIAL RJ",
        "SEGURANÇA PRESENTE",
        "PREFEITURA DE MARICÁ",
    ],
    "25º BPM - 4º CPA": [
        "Selecione o local",
        "25 BPM - RAS",
        "PREFEITURA DE BUZIOS",
        "PREFEITURA DE SAQUAREMA",
        "MUNICIPIO DE ARRAIAL DO CABO",
        "MUNICÍPIO DE ARARUAMA",
        "PREFEITURA DE CABO FRIO",
        "MUNICÍPIO DE IGUABA GRANDE",
    ],
}

OPTIONS_VAGASXLOCAIS_CPA = {
    "MUNICIPIO DE NITEROI": [
        "Selecione uma vaga",
        "APOIO A INTERVENCAO URBANISTICA DA PRE. DE NITEROI",
        "NITEROI MAIS SEGURA",
        "BARCAS SA  E TERMINAL",
    ],
    "IMPRENSA OFICIAL RJ": ["Selecione uma vaga", "IMPRENSA OFICIAL SEDE"],
    "SEGURANÇA PRESENTE": [
        "Selecione uma vaga",
        "NITEROI PRESENTE ICARAI POG",
        "NITEROI PRESENTE CENTRO POG",
        "NITEROI PRESENTE REGIAO OCEANICA POG",
    ],
    "PREFEITURA DE MARICÁ": [
        "Selecione uma vaga",
        "CERCO INTELIGENTE",
        "MÓDULO CALABOCA",
        "MÓDULO DE SEGURANÇA UBATIBA",
        "MÓDULO DO CAJU",
        "MÓDULO DE SEGURANÇA CAJUEIRO",
        "MÓDULO DE SEGURANÇA SÃO JOSÉ",
        "PATRULHAMENTO MARICA",
        "PB ACESSO AO MCMV INOÃ",
        "SETOR CENTRO",
        "SETOR ITAIPUAÇU",
        "SETOR PONTA NEGRA",
        "SETOR SÃO JOSÉ DO IMBASSAÍ",
        "SETOR INOÃ",
        "SETOR UBATIBA",
        "SETOR BAMBUÍ",
        "SETOR ITAIPUAÇU ITAOCAIA",
    ],
    "25 BPM - RAS": [
        "Selecione uma vaga",
    ],
    "PREFEITURA DE BUZIOS": [
        "Selecione uma vaga",
        "UMA BUZIOS MAIS SEGURA",
    ],
    "PREFEITURA DE SAQUAREMA": [
        "Selecione uma vaga",
        "DEPÓSITO MAIS SEGURO",
        "MÓDULO JACAREPIÁ",
        "MÓDULO TREVO LATINO MELO",
        "MÓDULO TREVO VILATUR",
        "SAQUAREMA MAIS SEGURA III",
        "VTR DE APOIO AO MODULO JACAREPIA",
    ],
    "MUNICIPIO DE ARRAIAL DO CABO": [
        "Selecione uma vaga",
        "POLICIAMENTO",
    ],
    "MUNICÍPIO DE ARARUAMA": [
        "Selecione uma vaga",
        "PATRULHAMENTO ARARUAMA MAIS SEGURA",
    ],
    "PREFEITURA DE CABO FRIO": [
        "Selecione uma vaga",
        "CABO FRIO LUGAR PARA TODOS NÓS NOTURNO",
    ],
    "MUNICÍPIO DE IGUABA GRANDE": [
        "Selecione uma vaga",
        "PATRULHAMENTO  DIA E NOITE",
    ],
}

OPTIONS_HORAMARCACAO = ["Selecione o horário", "06:00:00", "06:30:00", "07:00:00"]

OPTIONS_TURNOSERVICO = ["Selecione o turno de serviço", "8 h", "12 h", "24 h"]

OPTIONS_HORARIO = [
    "Selecione o horário de serviço",
    "06:00:00",
    "07:00:00",
    "08:00:00",
    "09:00:00",
    "10:00:00",
    "14:00:00",
    "16:00:00",
    "16:30:00",
    "18:00:00",
    "18:01:00",
    "19:00:00",
    "20:00:00",
    "21:30:00",
]
""" OPTIONS_HORARIO = [
    "Selecione o horário de serviço",
    "01:00:00",
    "01:30:00",
    "02:00:00",
    "02:30:00",
    "03:00:00",
    "03:30:00",
    "04:00:00",
    "04:30:00",
    "05:00:00",
    "05:30:00",
    "06:00:00",
    "06:30:00",
    "07:00:00",
    "07:30:00",
    "08:00:00",
    "08:30:00",
    "09:00:00",
    "09:30:00",
    "10:00:00",
    "10:30:00",
    "11:00:00",
    "11:30:00",
    "12:00:00",
    "12:30:00",
    "13:00:00",
    "13:30:00",
    "14:00:00",
    "14:30:00",
    "15:00:00",
    "15:30:00",
    "16:00:00",
    "16:30:00",
    "17:00:00",
    "17:30:00",
    "18:00:00",
    "18:01:00",
    "18:30:00",
    "19:00:00",
    "19:30:00",
    "20:00:00",
    "20:30:00",
    "21:00:00",
    "21:30:00",
    "22:00:00",
    "22:30:00",
    "23:00:00",
    "23:30:00",
    "00:00:00",
]
 """
